services:

  app-base: &app-base
    build:
      context: .
      dockerfile: ./Dockerfile

  app: &app
    <<: *app-base
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.chainlit:/app/.chainlit
    command:
      ["uv", "run", "fastapi", "run", "src/wordpress_chatbot/main.py", "--reload"]
    env_file:
    - path: ./envs/local.env
      required: true # default
    - path: ./.env
      required: false
    ports:
      - "8000:8000"


  app-tests: &app-tests
    <<: *app-base
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: >
       bash -c "uv run python -m pytest --doctest-modules"
