services:

  app-base: &app-base
    build:
      context: .
      dockerfile: ./Dockerfile

  app: &app
    <<: *app-base
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./parsed:/app/parsed
      - ./.chainlit:/app/.chainlit
    command:
      ["uv", "run", "chainlit", "run", "src/wordpress_chatbot/chat.py", "-w", "--host", "0.0.0.0"]
    env_file:
    - path: ./.env
      required: false
    ports:
      - "8000:8000"


  app-tests: &app-tests
    <<: *app-base
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    command: >
       bash -c "uv run python -m pytest --doctest-modules"


volumes:
  pgdata:
